[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Introduction to function calling in LLMs"
readme = "README.md"
authors = [
    { name = "janmazon", email = "jcamarer@student.42urduliz.com" }
]

requires-python = ">=3.10"

dependencies = [
    "llm-sdk",
    "numpy>=1.24",
    "pydantic>=2.13.5",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true, editable = true }
